### ISSUE TITLE
Browse Projects not working

### ISSUE THREAD

**Issue by vowelllDOE** [GSA/code-gov-web#672] opened 2018-10-05 19:04 UTC
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Steps to Reproduce (for bugs)

1. navigate to code.gov, the agency drop down is empty
2. click 'go' on the search
3. the /browse-projects just says 'loading' and no results are found

## Your Environment

* Version used: 
* Browser Name and version: Chrome Version 69.0.3497.100 
* Operating System and version (desktop or mobile): windows 10 desktop
* Link to your project:

**Comment by DanielJDufour** [comment] 2018-10-05 19:18
I'm having difficulty reproducing.  It's an odd error.  You're using Chrome, so that rules out a browser support/polyfill issue. 

1) The agencies not appearing in the drop down indicates that the api call to get the agencies isn't working for some reason.

2) @vowelllDOE , do you type anything into the search box?  If you click go without typing anything in, nothing should happen.
![image](https://user-images.githubusercontent.com/4313463/46555396-2298b580-c8b1-11e8-8b8c-44a3fc2def0b.png)

3) Browse projects not loading indicates that the API call is failing to load the repos, too.

@froi  and @saracope , could you try to reproduce the error and tell me if you notice anything in the console?

Additionally, @froi  could you do a quick check of the api call logs and let me know if you see anything? Thanks!

@vowelllDOE , next time this happens, could you do be a big favor and take a screenshot of your dev console?
![image](https://user-images.githubusercontent.com/4313463/46555568-bb2f3580-c8b1-11e8-8639-25e234d194f3.png)

Thank you all and I apologize again for this issue.  It's really stumping me at the moment.

**Comment by vowelllDOE** [comment] 2018-10-05 19:20
it's still happening
![image](https://user-images.githubusercontent.com/20361298/46555695-1e20cc80-c8b2-11e8-99df-37e1a7cc7ca5.png)

**Comment by DanielJDufour** [comment] 2018-10-05 19:29
@vowelllDOE , thank you.  This is very helpful.  It currently appears as if the issue is with the API.  The API key is correct, but the API call isn't working for some reason.  I'm going to create a separate issue in the api repo and post the link here.

**Comment by froi** [comment] 2018-10-07 04:01
Found the issue. The API gateway was rejecting all requests from `https://www.code.gov/`. The `www` subdomain has been added to the HTTP referer whitelist and is now working.

Before updating the HTTP referer whitelist:
<img width="1291" alt="screenshot 2018-10-06 23 55 51" src="https://user-images.githubusercontent.com/1918027/46578099-e73adb80-c9c3-11e8-8736-ac6fa135c4da.png">

After updating the HTTP referer whitelist:
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/1918027/46578096-c6728600-c9c3-11e8-92ab-7dc1fe0daa57.png">

@vowelllDOE Can you please confirm that it is working on your end before I close this issue?

Thanks again for submitting this issue to us.

**Comment by vowelllDOE** [comment] 2018-10-09 11:43
@froi it seems to be working this AM, yep.  Thanks for your work on this.  I'll let you know if it occurs again.

**Comment by DanielJDufour** [comment] 2018-10-09 13:18
thanks all! I'm closing issue now.

**Closed by DanielJDufour** 2018-10-09 13:18 UTC
Labels: [Problem] bug critical
